apiVersion: v1
kind: ConfigMap
metadata:
  name: memos-config
  namespace: memos-app
data:
  POSTGRES_DB: "memos"
  POSTGRES_USER: "memos_user"
  MEMOS_DRIVER: "postgres"
  MEMOS_INSTANCE_URL: "http://sharifi.osdl.ir"
