apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memos-data
  namespace: memos-app
spec:
  storageClassName: local-path
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
